WIP: Add expanding text box
elifesciences/elife-xpub pull request #1992
Opened 2019-05-16 09:43 UTC by petereast

#### Background

Adds and expanding text box to the SubmissionPage title field.

#### Any relevant tickets
closes #1667 

#### How has this been tested?
**Reviewers** ensure that these test requirements are also reviewed.

Please indicate the need for this change to be tested. If not please justify, if so then at what levels. 

- [ ] Unit / Integration tests
- [ ] Browser tests
- [ ] End2end tests

#### UI Changes

- [ ] Has been reviewed against Designs
- [ ] Necessary updates to styleguide

2019-05-16 10:45 UTC, erezmus requested changes

2019-05-16 10:45 UTC, erezmus commented on packages/component-submission/client/components/ExpandingTextField.js
> +  /* height: calc(${th('gridUnit')} * 6); */
remove commented line

2019-05-16 11:18 UTC, hdrury1 commented
I get an error when I try to access the review environment... do we need to update the AWS keys in the pipeline?

2019-05-17 09:53 UTC, Cooryd commented on packages/component-submission/client/pages/SubmissionPage.js
> +  // TODO: turn this ValidatedField into a richTextBox
remove comment if done

2019-05-17 10:13 UTC, Cooryd commented on packages/component-submission/client/components/ExpandingTextField.js
> +          rows={this.state.lines || minRows}
Is there a case where rows might be set to something less than `this.props.minRows`?

2019-05-20 14:29 UTC, erezmus approved these changes

2019-05-20 14:32 UTC, will-byrne approved these changes

2019-05-20 15:07 UTC, Cooryd approved these changes

2019-05-21 15:56 UTC, merged