2020 - rediect to a given config url on logout
elifesciences/elife-xpub pull request #2027
Opened 2019-05-24 15:07 UTC by Cooryd

#### Background

The user should be signed out of the journal and be redirected back to the journals home page if they log out of reviewer. This PR adds this redirect based on a config value after clearing the local apollo store and removing the reviewer session storage token.

#### Any relevant tickets

closes #2020

2019-05-24 15:14 UTC, erezmus approved these changes

2019-05-24 15:15 UTC, petereast approved these changes

2019-05-27 08:24 UTC, diversemix requested changes
I'd like to fully understand what is going on before this gets merged.

2019-05-28 13:13 UTC, diversemix approved these changes
Discussed in retro

2019-05-28 13:14 UTC, merged